export type Decisions={civic:boolean,fieldstone:boolean,atlas:boolean};
export type Scenario={quality:boolean,maxLead:number};
export const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);
export const percent=(n:number)=>(n*100).toFixed(1)+'%';
export const sum=(values:number[])=>values.reduce((a,b)=>a+b,0);
const round=(n:number)=>Math.round(n*100)/100;
export const vendors=[
 {name:'Meridian Office',short:'Meridian',initials:'MO',color:'#6e9788',format:'Email + XLSX',basis:'USD / each',score:86,weeks:6,window:'4–6 weeks',docs:['Meridian_quote.xlsx','Meridian_answers.pdf','Meridian_quality.pdf']},
 {name:'Civic Supply Co.',short:'Civic',initials:'CS',color:'#72909d',format:'Email + PDF',basis:'USD / 5-pack (seating)',score:82,weeks:8,window:'6–8 weeks',docs:['Civic_proposal.pdf','Civic_answers.docx','Civic_materials.pdf']},
 {name:'Kinetic Workplace',short:'Kinetic',initials:'KW',color:'#c5a025',format:'Email + DOCX',basis:'EUR / each',score:89,weeks:5,window:'3–5 weeks',docs:['Kinetic_offer.docx','Kinetic_answers.pdf','Kinetic_test_report.pdf']},
 {name:'Fieldstone Goods',short:'Fieldstone',initials:'FG',color:'#c7806b',format:'Email + PDF',basis:'USD / each',score:78,weeks:10,window:'8–10 weeks',docs:['Fieldstone_quote.pdf','Fieldstone_answers.docx','Fieldstone_warranty.pdf']},
 {name:'Atlas Contracting',short:'Atlas',initials:'AC',color:'#263d4b',format:'Email + scan',basis:'Mixed each / pack',score:84,weeks:7,window:'5–7 weeks',docs:['Atlas_scan.jpg','Atlas_answers.pdf','Atlas_installation.pdf']}
];
const schedule:[string,string,number,string,number,string][]=[
 ['Haven task chair','Seating',90,'ea',385,'Mesh back, adjustable lumbar'],['Haven task chair, graphite','Seating',30,'ea',412,'Fabric seat, ergonomic arms'],['Lumen sit–stand desk','Desks',120,'ea',685,'1400 × 700 mm, dual motor'],['Lumen desk cable tray','Desks',120,'ea',34,'Powder-coated steel, 600 mm'],['Arc mobile pedestal','Storage',80,'ea',176,'3-drawer, lockable'],['Arc 2-drawer lateral file','Storage',12,'ea',448,'900 mm width, anti-tilt'],['Northstar meeting table','Tables',6,'ea',1240,'2400 × 1200 mm, 8 seats'],['Meeting chair, upholstered','Seating',48,'ea',218,'Stackable, contract fabric'],['Focus desk screen','Acoustics',100,'ea',89,'1200 × 400 mm, PET felt'],['Dual monitor arm','Accessories',120,'ea',126,'VESA, 2–9 kg each'],['Single monitor arm','Accessories',12,'ea',74,'VESA, 2–9 kg'],['Desk power module','Electrical',120,'ea',59,'2 AC + USB-C'],['Visitor chair','Seating',20,'ea',164,'Upholstered, sled base'],['Reception desk','Reception',1,'ea',2860,'2400 mm, accessible return'],['Reception lounge chair','Lounge',4,'ea',790,'Contract fabric, timber base'],['Breakout table, round','Tables',8,'ea',375,'900 mm diameter'],['Breakout stool','Seating',32,'ea',142,'Counter height, footrest'],['Locker bank, 12 doors','Storage',10,'ea',1120,'Digital locks, steel'],['Coat stand','Accessories',8,'ea',68,'Weighted base'],['Line floor lamp','Lighting',12,'ea',158,'LED, dimmable'],['Grid whiteboard 48 in','Accessories',10,'ea',134,'Magnetic, wall mounted'],['Grid whiteboard 72 in','Accessories',6,'ea',219,'Magnetic, wall mounted'],['Drift planter, medium','Wellbeing',16,'ea',96,'400 mm, liner included'],['Drift planter, large','Wellbeing',8,'ea',188,'600 mm, liner included'],['Common room sofa','Lounge',4,'ea',1495,'3-seat, contract fabric'],['Common room ottoman','Lounge',8,'ea',295,'600 × 600 mm'],['Quiet pod, single','Acoustics',4,'ea',7850,'Ventilation, power, acoustic lining'],['Quiet pod, duo','Acoustics',2,'ea',12450,'2-person, ventilation and power'],['Wayfinding package','Signage',1,'lot',3450,'3 floors, design and installation'],['Installation and freight','Services',1,'lot',8200,'Phased delivery, floor protection, disposal']
];
export const items=schedule.map((r,i)=>({id:'L'+String(i+1).padStart(2,'0'),name:r[0],category:r[1],qty:r[2],unit:r[3],base:r[4],spec:r[5]}));
const categoryFactors:Record<string,number[]>={Seating:[1,.97,1.08,.93,1.04],Desks:[1,.98,1.04,.95,1.02],Storage:[1,1.05,1.01,.94,.98],Tables:[1,1.04,1.06,.92,1.03],Acoustics:[1,1.08,.98,.97,1.02],Accessories:[1,.97,1.04,.92,1.01],Electrical:[1,1.03,1.06,.94,.99],Reception:[1,1.02,1.08,.96,1.05],Lounge:[1,1.04,1.03,.94,.99],Lighting:[1,.99,1.02,.96,1.04],Wellbeing:[1,1.06,1.02,.93,1.04],Signage:[1,1.03,1.08,.97,1.01],Services:[1,.96,1.08,.93,1.02]};
const perturbations=[.012,-.019,.008,.024,-.007,.016,-.022,.003,-.013,.018,.006,-.011,.025,-.018,.009,.014,-.004,.021,-.016,.002];
export function rawPrice(i:number,v:number){if(v===4&&[20,23,28].includes(i))return null;if(i===29&&v===1)return 6200;if(i===29&&v===3)return 7600;if(i===2&&v===4)return 1260;return round(items[i].base*categoryFactors[items[i].category][v]*(1+perturbations[(i*7+v*3)%perturbations.length]));}
export function quote(i:number,v:number,d:Decisions):{raw:number|null,landed:number|null,status:'ready'|'review'|'missing'}{const raw=rawPrice(i,v);if(raw===null)return {raw:null,landed:null,status:'missing'};if(i===29&&v===1)return {raw,landed:d.civic?8750:null,status:d.civic?'ready':'review'};if(i===29&&v===3)return {raw,landed:d.fieldstone?5400:null,status:d.fieldstone?'ready':'review'};if(i===2&&v===4)return {raw,landed:d.atlas?630:null,status:d.atlas?'ready':'review'};const landed=v===1&&items[i].category==='Seating'?raw*Math.ceil(items[i].qty/5)*5/items[i].qty:raw;return {raw,landed,status:'ready'};}
export function source(i:number,v:number,d:Decisions){const q=quote(i,v,d),item=items[i],vendor=vendors[v];const location=vendor.docs[0]+' · '+(v===0?'Quote!F'+(i+2):v===2?'table 1, row '+(i+2):'page '+(Math.floor(i/8)+1)+', '+item.id);let raw=q.raw===null?'This line is not quoted.':money(q.raw)+' / '+item.unit+'; delivery included.';let formula='No conversion; USD / '+item.unit;let display=q.raw===null?'Not quoted':money(q.raw);if(v===1&&item.category==='Seating'&&q.raw!==null){raw=money(q.raw*5)+' per pack of 5 chairs, delivery included.';formula=money(q.raw*5)+' ÷ 5 = '+money(q.raw)+' / chair';display=money(q.raw*5)+' / 5-pack';}if(v===2&&q.raw!==null){const euros=q.raw/1.1;raw='€'+euros.toFixed(6)+' / '+item.unit+', delivered.';formula='EUR price × 1.10 USD/EUR = '+money(q.raw)+'. Fixed illustrative event FX, not live.';display='€'+euros.toFixed(2);}
if(v===1&&item.category==='Seating'&&q.raw!==null&&item.qty%5!==0){formula+='; full packs require '+Math.ceil(item.qty/5)*5+' purchased for '+item.qty+' requested. Effective landed rate: '+money(q.landed!)+' / requested chair.';}
if(i===29&&v===1){raw='Installation included. Site services billed at cost. Stated installation amount: $6,200.';formula=d.civic?'Recorded supplier clarification confirms fixed landed $8,750.':'Excluded: mandatory site services have no stated price.';}if(i===29&&v===3){raw='Attachment: $7,600. Revised email: please use $5,400.';formula=d.fieldstone?'Buyer recorded revised email as authoritative: $5,400.':'Excluded: competing source prices require a buyer decision.';}if(i===2&&v===4){raw='$1,260 / pack. Pack quantity not stated.';formula=d.atlas?'Supplier confirmed 2 desks / pack. $1,260 ÷ 2 = $630 per desk.':'Excluded: pack quantity unknown.';}if(q.raw===null)formula='No imputation. Missing offers cannot be allocated.';return {raw,location,formula,display};}
export function calculate(d:Decisions,s:Scenario){const allocations:{line:number,vendor:number,unit:number,total:number}[]=[];const suppliers=vendors.map(()=>({count:0,total:0}));items.forEach((item,i)=>{const choices=vendors.map((v,j)=>({vendor:j,unit:quote(i,j,d).landed,score:v.score,weeks:v.weeks})).filter(x=>x.unit!==null&&(!s.quality||x.score>=80)&&(!s.maxLead||x.weeks<=s.maxLead)).sort((a,b)=>a.unit!-b.unit!);if(choices.length){const c=choices[0],total=round(c.unit!*item.qty);allocations.push({line:i,vendor:c.vendor,unit:c.unit!,total});suppliers[c.vendor].count++;suppliers[c.vendor].total=round(suppliers[c.vendor].total+total);}});return {allocations,suppliers,total:round(sum(allocations.map(x=>x.total)))};}
export const questions=[
 {name:'Warranty coverage',requirement:'5 years requested on workpoint furniture',answers:['5 years','3 years','5 years','2 years','5 years']},
 {name:'Ergonomic test evidence',requirement:'Attach applicable ANSI/BIFMA test report',answers:['Report attached','Report attached','Report attached','Partial report','Report attached']},
 {name:'Material emissions',requirement:'Attach low-VOC or equivalent certificate',answers:['Certificate attached','Certificate attached','Certificate attached','Evidence pending','Certificate attached']},
 {name:'Delivery window',requirement:'State maximum weeks from order',answers:['4–6 weeks','6–8 weeks','3–5 weeks','8–10 weeks','5–7 weeks']},
 {name:'Recycled content',requirement:'Declare material content and evidence',answers:['28%, statement attached','22%, statement attached','38%, statement attached','Claim only, 20%','30%, statement attached']},
 {name:'Installation scope',requirement:'Freight, assembly, protection and disposal',answers:['All included','Site services at cost','All included','Revised price conflicts','All included']},
 {name:'Payment terms',requirement:'Net 45 requested',answers:['Net 45','Net 30','Net 45','50% advance','Net 45']},
 {name:'Quote validity',requirement:'60 days requested',answers:['60 days','45 days','60 days','30 days','60 days']},
 {name:'Phased delivery',requirement:'Two phases across three occupied floors',answers:['Accepted','Subject to site survey','Accepted','Extra handling possible','Accepted']},
 {name:'Defect response',requirement:'State replacement and service SLA',answers:['5 business days','10 business days','3 business days','15 business days','7 business days']},
 {name:'Product substitutions',requirement:'Declare deviations from specification',answers:['None','None','None','Alternative chair fabric','Three lines not quoted']},
 {name:'Minimum order',requirement:'Identify MOQ / pack constraints',answers:['No MOQ','Seating packs of 5','No MOQ','No MOQ','Desk pack size unclear']}
];
